dtksh: update ksh93

diff --git a/cde/programs/dtksh/ksh93/bin/shtests b/cde/programs/dtksh/ksh93/bin/shtests
--- a/cde/programs/dtksh/ksh93/bin/shtests
+++ b/cde/programs/dtksh/ksh93/bin/shtests
@@ -1,37 +1,55 @@
-#! /bin/sh
-# Wrapper script to run the ksh93 regression tests without requiring nmake.
-# By Martijn Dekker <martijn@inlv.org> 2020-05-14
-# Public domain. http://creativecommons.org/publicdomain/zero/1.0/
+# Wrapper script to run the ksh93 regression tests directly.
+# By Martijn Dekker <martijn@inlv.org> 2020-05-14, 2023-03-17, 2024-03-05
+# Public domain. https://creativecommons.org/publicdomain/zero/1.0/
 #
 # The manual: bin/shtests --man
 # Brief help: bin/shtests --help
 #
 # By default, this runs your compiled arch/*/bin/ksh.
-#
-# Note: The test suite actually uses $SHELL to indicate the shell to test. But
-# we cannot use the $SHELL environment value on entry to this wrapper script,
-# as that is already used for the user's default login shell on most systems.
 
-# Process and remove any assignment-argument indicating the shell to test
+# Escape from a non-POSIX shell
+min_posix=/if/this/is/csh/ignore/the/error/message || exec sh $0:q $argv:q
+# ('test X -ef Y' is technically non-POSIX, but practically universal)
+min_posix='test / -ef / && path=Bad && case $PATH in (Bad) exit 1;; esac && '\
+'PWD=Bad && cd -P -- / && case $PWD in (/) ;; (*) exit 1;; esac && '\
+'! { ! case x in ( x ) : ${0##*/} || : $( : ) ;; esac; } && '\
+'trap "exit 0" 0 && exit 1'
+if	(eval "$min_posix") 2>/dev/null
+then	: good shell
+else	"$SHELL" -c "$min_posix" 2>/dev/null && exec "$SHELL" -- "$0" ${1+"$@"}
+	sh -c "$min_posix" 2>/dev/null && exec sh -- "$0" ${1+"$@"}
+	DEFPATH=`getconf PATH` 2>/dev/null || DEFPATH=/usr/xpg4/bin:/bin:/usr/bin:/sbin:/usr/sbin
+	PATH=$DEFPATH:$PATH
+	export PATH
+	sh -c "$min_posix" 2>/dev/null && exec sh -- "$0" ${1+"$@"}
+	echo "$0: Can't escape from obsolete or broken shell. Run me with a POSIX shell." >&2
+	exit 128
+fi
+
+# bin/package will have set $SHELL to our ksh.
+# Allow override by passing SHELL= or KSH= as arguments.
 for arg do
 	case $arg in
 	( SHELL=* | KSH=* )
-		KSH=${arg#*=} ;;
+		export KSH=${arg#*=} ;;
 	( * )	set -- "$@" "$1" ;;
 	esac
 	shift
 done
 
-# Find root dir of ksh source
-mydir=$(dirname "$0") \
-&& mydir=$(CDPATH='' cd -P -- "$mydir/.." && printf '%sX' "$PWD") \
-&& mydir=${mydir%X} \
-|| exit
-myarch=$("$mydir/bin/package" host type) || exit
+# Relaunch with necessary environment stuff from bin/package
+case ${HOSTTYPE+h}${INSTALLROOT+i}${PACKAGEROOT+p}${LD_LIBRARY_PATH+l} in
+hipl)	;;
+*)	mydir=$(dirname "$0") \
+	&& mydir=$(CDPATH='' cd -P -- "$mydir/.." && printf '%sX' "$PWD") \
+	&& mydir=${mydir%X} \
+	|| exit
+	exec "$mydir/bin/package" use "$mydir" "$0" "$@" ;;
+esac
 
 # Check if there is a ksh to test.
 case ${KSH+set} in
-( '' )	KSH=$mydir/arch/$myarch/bin/ksh ;;
+( '' )	KSH=$SHELL ;;
 esac
 if ! test -x "$KSH" || ! test -f "$KSH"; then
 	printf '%s: shell not found: %s\n' "${0##*/}" "$KSH" >&2
@@ -45,10 +63,8 @@ KSH=$(CDPATH='' cd -P -- "$(dirname "$KSH")" \
 && KSH=${KSH%X}
 
 # Run the test suite
-CDPATH='' cd -P -- "$mydir/src/cmd/ksh93/tests" || exit
+CDPATH='' cd -P -- "$PACKAGEROOT/src/cmd/ksh93/tests" || exit
 SHELL=$KSH
-INSTALLROOT=${INSTALLROOT:-$mydir/arch/$myarch}
-export SHELL INSTALLROOT
 unset -v KSH
 printf '#### Regression-testing %s ####\n' "$SHELL"
 exec "$SHELL" shtests "$@"
diff --git a/cde/programs/dtksh/ksh93/src/cmd/ksh93/features/externs b/cde/programs/dtksh/ksh93/src/cmd/ksh93/features/externs
--- a/cde/programs/dtksh/ksh93/src/cmd/ksh93/features/externs
+++ b/cde/programs/dtksh/ksh93/src/cmd/ksh93/features/externs
@@ -1,15 +1,29 @@
-hdr	nc,exec_attr
+hdr	nc
 mem	exception.name,_exception.name math.h
-lib	setreuid,setregid,nice,fork,spawnveg,fchdir
-lib	pathnative,pathposix,fts_notify
+lib	setreuid,setregid
 lib	memcntl sys/mman.h
-lib	getexecuser,free_execattr exec_attr.h -lsecdb
+
+# for main.c fixargs():
+lib,sys	pstat
+lib	setproctitle
 
 reference	unistd.h
 
 extern	nice		int	(int)
 extern	setreuid	int	(uid_t,uid_t)
 extern	setregid	int	(gid_t,gid_t)
+
+tst	note{ does the system support #! interpreter paths }end cross{
+	cat > "$EXECROOT/file$$" <<!
+	#! $(command -v env) true
+	exit 1
+	!
+	chmod 755 "$EXECROOT/file$$"
+	if	"$EXECROOT/file$$" 2>/dev/null
+	then	echo "#define SHELLMAGIC	1"
+	fi
+	rm -f "$EXECROOT/file$$"
+}end
 
 tst	note{ determining default number of extra bytes per argument for arguments list }end output{
 	/*
@@ -26,7 +40,7 @@ tst	note{ determining default number of extra bytes per argument for arguments l
 	 * So, operating systems are free to consume ARG_MAX space in whatever bizarre way they want, and
 	 * may even come up with more innovative ways to waste buffer space in future. This test assumes
 	 * that null terminators are included in the total, because why wouldn't they be? It builds a
-	 * dummy arguments list and tries fork(2)/execve(2) to figure how how many extra bytes to add to
+	 * dummy arguments list and tries fork(2)/execvp(2) to figure how how many extra bytes to add to
 	 * each argument to account for pointers and whatnot, and outputs that (_arg_extrabytes) as a
 	 * default value for command_xargs() in path.c. We still cannot entirely rely on this value on all
 	 * systems, so path_spawn() in path.c is able to increase it at runtime if E2BIG still occurs.
@@ -35,7 +49,7 @@ tst	note{ determining default number of extra bytes per argument for arguments l
 	#include <ast.h>
 	#include <error.h>
 	#include <sfio.h>
-	#include <stak.h>
+	#include <stk.h>
 	#include <wait.h>
 
 	int main(int argc,char *argv[])
@@ -68,12 +82,12 @@ tst	note{ determining default number of extra bytes per argument for arguments l
 				int bytec;
 
 				error_info.id="_arg_extrabytes test (child)";
-				argv = (char **)stakalloc((argmax / 2 + 1) * sizeof(char*));
+				argv = stkalloc(stkstd, (argmax / 2 + 1) * sizeof(char*));
 				argc = bytec = 0;
 				while(bytec < argmax)
 				{
 					if(argc==0)
-						argv[argc] = "/usr/bin/env";
+						argv[argc] = "env";
 					else if(argc==1)
 						argv[argc] = "true";
 					else
@@ -82,14 +96,14 @@ tst	note{ determining default number of extra bytes per argument for arguments l
 					bytec += strlen(argv[argc]) + 1 + extra_bytes;
 					argc++;
 				}
-				argv[argc] = (char*)0;
-				if(execve(argv[0], argv, environ) < 0)
+				argv[argc] = NULL;
+				if(execvp(argv[0], argv) < 0)
 				{
 					if(errno == E2BIG)
 						return 1;
 					else
 					{
-						error(ERROR_SYSTEM|2, "execve failed");
+						error(ERROR_SYSTEM|2, "execvp failed");
 						return 2;
 					}
 				}
@@ -135,4 +149,81 @@ tst	note{ determining default number of extra bytes per argument for arguments l
 	}
 }end fail{
 	echo "#define _arg_extrabytes	sizeof(char*)	/* BUG: test failed; assuming pointer size */"
+}end
+
+tst	note{ determining size of PID variables }end output{
+	#include <ast.h>
+	#include <sfio.h>
+	int main(void)
+	{
+		const int s = sizeof(pid_t);
+		char *a;
+		Sfio_t *b;
+		/*
+		 * For $$, $PPID, ${.sh.pid} and ${.sh.ppid} to work correctly, the size
+		 * of pid_t must be one of the integer sizes supported by nv_getval().
+		 * If there is ever a system where this test returns 1, then both this
+		 * test and nv_getval() must learn a new integer size attribute.
+		 */
+		if(s==sizeof(int16_t))
+			a="NV_INTEGER|NV_SHORT";
+		else if(s==sizeof(int32_t))
+			a="NV_INTEGER";
+		else if(s==sizeof(Sflong_t))
+			a="NV_INTEGER|NV_LONG";
+		else
+			return 1;
+		/* write NV_PID attribute definition */
+		sfprintf(sfstdout,"#define NV_PID\t(%s)\t/* integer attribute(s) corresponding to sizeof(pid_t)==%d */\n",a,s);
+		/* show nice test result output on FD 9 */
+		b = sfstropen();
+		sfprintf(b," %s (%d bytes) ... ",a,s);
+		a = sfstruse(b);
+		write(9,a,strlen(a));
+		return 0;
+	}
+}end fail{
+	echo "$0: cannot determine size of PID variables" >&2
+	exit 1
+}end
+
+# execve(3) breakage on Android/Termux (early versions of API 35)
+tst	execve_ignores_argv0 note{ does execve(3) ignore the specified argv[0] }end output{
+	#include <string.h>
+	#include <unistd.h>
+	extern char **environ;
+	/* Check if argv[0] can be set to "TEST_OK" while exec'ing self */
+	int main(int argc, char *argv[])
+	{
+		char *orig0 = argv[0], *newenv[2], b[64];
+		int i;
+		sprintf(b,"_KSH_EXECVE_TEST_%d=y",(int)getpid());
+		newenv[0] = b;
+		newenv[1] = NULL;
+		/* check if we've already been re-exec'ed */
+		for (i = 0; environ[i]; i++)
+			if (strcmp(environ[i],newenv[0])==0)
+				return !(strcmp(argv[0],"TEST_OK")!=0);
+		/* exec self */
+		argv[0] = "TEST_OK";
+		execve(orig0,argv,newenv);
+		return 128;
+	}
+}end
+tst	execve_dir_enoexec note{ does execve(3) set errno to ENOEXEC when trying to execute a directory }end output{
+	#include <sys/stat.h>
+	#include <unistd.h>
+	#include <errno.h>
+	extern char **environ;
+	int main(int argc, char *argv[])
+	{
+		char	dirname[64];
+		int	e;
+		sprintf(dirname,".dir.%u",(unsigned)getpid());
+		mkdir(dirname,0777);
+		execve(dirname,argv,environ);
+		e = errno;
+		rmdir(dirname);
+		return !(e == ENOEXEC);
+	}
 }end
diff --git a/cde/programs/dtksh/ksh93/src/cmd/ksh93/tests/shtests b/cde/programs/dtksh/ksh93/src/cmd/ksh93/tests/shtests
--- a/cde/programs/dtksh/ksh93/src/cmd/ksh93/tests/shtests
+++ b/cde/programs/dtksh/ksh93/src/cmd/ksh93/tests/shtests
@@ -1,3 +1,23 @@
+########################################################################
+#                                                                      #
+#               This software is part of the ast package               #
+#          Copyright (c) 1995-2012 AT&T Intellectual Property          #
+#          Copyright (c) 2020-2024 Contributors to ksh 93u+m           #
+#                      and is licensed under the                       #
+#                 Eclipse Public License, Version 2.0                  #
+#                                                                      #
+#                A copy of the License is available at                 #
+#      https://www.eclipse.org/org/documents/epl-2.0/EPL-2.0.html      #
+#         (with md5 checksum 84283fa8859daf213bdda5a9f8d1be1d)         #
+#                                                                      #
+#                  David Korn <dgk@research.att.com>                   #
+#                 Glenn Fowler <gsf@research.att.com>                  #
+#                  Martijn Dekker <martijn@inlv.org>                   #
+#            Johnothan King <johnothanking@protonmail.com>             #
+#                      Phi <phi.debian@gmail.com>                      #
+#                                                                      #
+########################################################################
+
 : ksh regression test harness :
 
 command=shtests
@@ -8,19 +28,17 @@ valgrindflags='--xml=yes --log-file=/dev/null --track-origins=yes --read-var-inf
 
 USAGE=$'
 [-s8?
-@(#)$Id: shtests (ksh 93u+m) 2021-12-28 $
+@(#)$Id: shtests (ksh 93u+m) 2024-12-28 $
 ]
 [-author?David Korn <dgk@research.att.com>]
 [-author?Glenn Fowler <gsf@research.att.com>]
+[-author?Contributors to https://github.com/ksh93/ksh]
 [-copyright?(c) 2000-2012 AT&T Intellectual Property]
-[-copyright?(c) 2020-2022 Contributors to https://github.com/ksh93/ksh]
+[-copyright?(c) 2020-2024 Contributors to ksh 93u+m]
 [-license?https://www.eclipse.org/org/documents/epl-2.0/EPL-2.0.html]
 [+NAME?shtests - ksh regression test harness]
 [+DESCRIPTION?\bshtests\b is the \bksh\b(1) regression test harness for
-    \b$SHELL\b or \bksh\b if \bSHELL\b is not defined and exported. If
-    none of the \b--posix\b \b--utf8\b \b--compile\b options are specified then
-    all three are enabled for most tests, whereas only \b--posix\b \b--utf8\b
-    are enabled for the \bpty\b tests for the interactive shell.]
+    \b$SHELL\b (or \bksh\b if \bSHELL\b is not defined and exported).]
 [+INPUT FILES?\bshtests\b regression test files are shell scripts that
     run in an environment controlled by \bshtests\b. An identification
     message is printed before and after each test on the standard output.
@@ -29,8 +47,6 @@ USAGE=$'
         [+unset LANG]
         [+unset LC_ALL]
         [+LC_NUMERIC=C?\b.\b radix point assumed by all test scripts.]
-        [+VMALLOC_OPTIONS=abort?\bvmalloc\b(1) arena checking enabled
-            with \babort(2)\b on error.]
     }
 [c:compile?Run test scripts using \bshcomp\b(1).]
 [d:debug?Enable \bshtests\b execution trace.]
@@ -43,17 +59,17 @@ USAGE=$'
 [t!:time?Include the current date/time in the test identification
     messages.]
 [u:utf8?Run the test scripts in the ast-specific C.UTF-8 locale.]
-[v!:vmalloc_options?Run tests with \bVMALLOC_OPTIONS=abort\b. Test
-    script names matching \b'$timesensitive$'\b are run with
-    \bVMALLOC_OPTIONS\b unset.]
-[V:valgrind?Set \b--novmalloc_options\b and run the test scripts with
+[V:valgrind?Run the test scripts with
     \bvalgrind\b(1) on \bksh\b. If \b$SHELL-g\b exists and is executable,
     then it is used instead of \b$SHELL\b.]
 [x:trace?Enable script execution trace.]
+[+?If none of the \b--posix\b \b--utf8\b \b--compile\b options are specified,
+    then all three are enabled for most tests, whereas only \b--posix\b
+    \b--utf8\b are enabled for the \blocale.sh\b and \bpty.sh\b tests.]
 
 [ test.sh ... ] [ name=value ... ]
 
-[+SEE ALSO?\bksh\b(1), \bregress\b(1), \brt\b(1)]
+[+SEE ALSO?\bksh\b(1), \bregress\b(1)]
 '
 
 function usage
@@ -176,8 +192,6 @@ trap + $(kill -l)	# unadvertised -- set all signals to SIG_DFL
 
 integer compile=-1 posix=-1 utf8=-1
 integer debug=0 keep=0 locale=0 time=1
-typeset vmalloc_options=abort trace= valgrind=
-vmalloc_options= #XXX# until multi-region vmalloc trace fixed #XXX#
 
 while	getopts -a $command "$USAGE" OPT
 do	case $OPT in
@@ -198,13 +212,7 @@ do	case $OPT in
 		;;
 	u)	utf8=$OPTARG
 		;;
-	v)	if	(( OPTARG ))
-		then	vmalloc_options=abort
-		else	vmalloc_options=
-		fi
-		;;
 	V)	valgrind="${VALGRIND:-valgrind} ${VALGRINDFLAGS:-$valgrindflags}"
-		vmalloc_options=
 		;;
 	x)	trace=-x
 		;;
@@ -246,12 +254,8 @@ then	utf8=0
 	fi
 else	unset LANG ${!LC_*}
 fi
-if	[[ $VMALLOC_OPTIONS ]]
-then	vmalloc_options=$VMALLOC_OPTIONS
-else	VMALLOC_OPTIONS=$vmalloc_options
-fi
-[[ $VMALLOC_OPTIONS ]] || timesensitive=.
-export PATH PWD SHCOMP SHELL VMALLOC_OPTIONS
+timesensitive=.
+export PATH PWD SHCOMP SHELL
 PWD=$(pwd)
 SHELL=${SHELL-ksh}
 case $0 in
@@ -264,6 +268,7 @@ case $SHELL in
 */*)	SHELL=$d/$SHELL;;
 *)	SHELL=$(whence $SHELL);;
 esac
+export userPATH=$PATH  # in case test scripts need it
 PATH=$(
 	builtin getconf 2>/dev/null || PATH=/run/current-system/sw/bin:/usr/xpg7/bin:/usr/xpg6/bin:/usr/xpg4/bin:/bin:/usr/bin:$PATH
 	getconf PATH 2>/dev/null
@@ -272,10 +277,13 @@ if	[[ -d /usr/ucb ]]
 then	PATH=$PATH:/usr/ucb
 fi
 PATH=$PATH:$d
-if	[[ $INSTALLROOT && -r $INSTALLROOT/bin/.paths ]]
-then	PATH=$INSTALLROOT/bin:$PATH
+if	[[ ! -v INSTALLROOT || $INSTALLROOT != /* ]]
+then	echo "$0: cannot continue: INSTALLROOT must be set" >&2
+	echo "$0: invoke me after 'bin/package use', or via 'bin/shtests' or 'bin/package test'" >&2
+	exit 1
 fi
-if	[[ ${SHELL%/*} != $INSTALLROOT/bin ]]
+PATH=$INSTALLROOT/bin:$PATH
+if	[[ ${SHELL%/*} != $INSTALLROOT/bin && ${SHELL%/*} != $INSTALLROOT/dyn/bin ]]
 then	PATH=${SHELL%/*}:$PATH
 fi
 if	[[ ! $SHCOMP ]]
@@ -287,6 +295,12 @@ then	s=${SHELL:##*sh}
 	then	SHCOMP=${s%-g}
 	else	SHCOMP=shcomp
 	fi
+fi
+
+# when testing a shell outside of INSTALLROOT, make sure libraries in INSTALLROOT are not loaded
+# The variables unset below should be the same ones that are set for 'test' or 'use' in bin/package
+if	! [[ ${SHELL%/*} -ef $INSTALLROOT/bin || ${SHELL%/*} -ef $INSTALLROOT/dyn/bin ]]
+then	unset -v LD_LIBRARY_PATH LIBPATH SHLIB_PATH DYLD_LIBRARY_PATH LIBRARY_PATH C_INCLUDE_PATH
 fi
 
 tmp=$(
@@ -306,13 +320,28 @@ fi
 export HOME=$tmp
 
 # make the SHOPT_* macros available to the tests as environment variables
+command unset "${!SHOPT_@}" 2>/dev/null
 SHOPT()
 {
 	[[ $1 == *=* ]] && eval "export SHOPT_${ printf %q "${1%%=*}"; }=${ printf %q "${1#*=}"; }"
 }
 . "${SHOPTFILE:-../SHOPT.sh}"
 unset -f SHOPT
-[[ -n $SHOPT_MULTIBYTE ]] || SHOPT_MULTIBYTE=$( LC_ALL=C.UTF-8; x=$'\xc3\xa9'; print $(( ${#x}==1 )) )
+# override with probed values from shopt.h:
+# change '#define SHOPT_foo = bar' to 'export SHOPT_foo=bar' and evaluate
+if	[[ -f $INSTALLROOT/src/cmd/ksh93/shopt.h ]] &&
+	i=$(sed -n $'/^#[ \t]*define[ \t][ \t]*SHOPT_/ {
+				s/.*define[ \t][ \t]*//
+				s/[ \t][ \t]*/=/
+				s/^/export /
+				p
+			}' "$INSTALLROOT"/src/cmd/ksh93/shopt.h)
+then	eval "$i" || exit
+else	echo "$0: cannot grep shopt.h" >&2
+	exit 1
+fi
+
+SHOPT_MULTIBYTE=$( LC_ALL=C.UTF-8; x=$'\xc3\xa9'; print $(( ${#x}==1 )) )
 if	(( !SHOPT_MULTIBYTE && utf8 && !posix && !compile ))
 then	echo "-u/--utf8 is unavailable because multibyte support was not compiled in." >&2
 	exit 1
@@ -346,6 +375,7 @@ do	[[ $i == *.sh ]] || i+='.sh'
 	t=$(	case $i in
 		glob.sh)	grep -c '^[[:blank:]]*test_[a-z]\{3,\}' $i ;;
 		leaks.sh)	grep -c ^TEST $i ;;
+		printf.sh)	grep -c -E '([[:blank:]]err_exit|^[[:blank:]]*T)[[:blank:]]' $i ;;
 		pty.sh)		grep -c 'tst ' $i ;;
 		*)		grep -c err_exit $i ;;
 		esac	)
@@ -356,9 +386,6 @@ do	[[ $i == *.sh ]] || i+='.sh'
 	fi
 	u=${i##*/}
 	u=${u%.sh}
-	if	[[ $i == $timesensitive ]]
-	then	VMALLOC_OPTIONS=
-	fi
 	if	(( posix || utf8 ))
 	then	locales=
 		(( posix )) && locales+=" ${LANG:-C}"
@@ -403,8 +430,8 @@ do	[[ $i == *.sh ]] || i+='.sh'
 			esac
 		done
 	fi
-	# Skip pty tests for shcomp, unless -c was explicitly specified (compile==2)
-	if	[[ compile -gt 0 && ! ($u == pty && compile -lt 2) ]]
+	# Skip certain tests for shcomp, unless -c was explicitly specified (compile==2)
+	if	[[ compile -gt 0 && ! (compile -lt 2 && ($u == 'locale' || $u == 'pty')) ]]
 	then	c=$tmp/shcomp-$u.ksh
 		o="$u(shcomp)"
 		echo test $o begins ${time:+"at $(date +%Y-%m-%d+%H:%M:%S)"}
@@ -438,9 +465,6 @@ do	[[ $i == *.sh ]] || i+='.sh'
 		cd "$OLDPWD" || exit
 		if	(( !keep ))
 		then	rm -rf "$tmp_s" "$c"
-		fi
-		if	[[ $i == $timesensitive ]]
-		then	VMALLOC_OPTIONS=$vmalloc_options
 		fi
 	fi
 done
diff --git a/cde/programs/dtksh/ksh93/src/lib/libast/features/common b/cde/programs/dtksh/ksh93/src/lib/libast/features/common
--- a/cde/programs/dtksh/ksh93/src/lib/libast/features/common
+++ b/cde/programs/dtksh/ksh93/src/lib/libast/features/common
@@ -1,10 +1,7 @@
 iff	AST_COMMON
 hdr	pthread,stdarg,stddef,stdint,inttypes,types,unistd
 sys	types
-typ	long.double,size_t,ssize_t
 typ	__va_list stdio.h
-
-mac	SF_APPEND,SF_CLOSE	sys/stat.h sys/socket.h
 
 std	noreturn note{ noreturn ok }end compile{
 	#include <stdlib.h>
@@ -14,15 +11,22 @@ std	noreturn note{ noreturn ok }end compile{
 }end
 
 cat{
-	#pragma clang diagnostic ignored "-Wdeprecated-register"
+	#if __clang__
+	#pragma clang diagnostic ignored "-Wmissing-braces"
 	#pragma clang diagnostic ignored "-Wparentheses"
 	#pragma clang diagnostic ignored "-Wstring-plus-int"
 	#pragma clang diagnostic ignored "-Wunused-value"
+	#elif __GNUC__
+	#pragma GCC diagnostic ignored "-Wpragmas"
+	#pragma GCC diagnostic ignored "-Wmissing-braces"
+	#pragma GCC diagnostic ignored "-Wparentheses"
 	#pragma GCC diagnostic ignored "-Wunused-result"
+	#pragma GCC diagnostic ignored "-Wunused-value"
+	#endif
 
-	/* AST backwards compatibility macros */
+	/* AST backward compatibility macros */
 	#undef	_NIL_
-	#define	_NIL_(x)	((x)0)
+	#define	_NIL_(x)	NULL
 	#undef	_STD_
 	#define	_STD_		1
 	#undef	_ARG_
@@ -41,12 +45,6 @@ cat{
 	#define	__STD_C		1
 	#undef	Void_t
 	#define	Void_t		void
-
-	/* disable non-standard Linux/GNU inlines */
-	#ifdef __GNUC__	
-	#	undef	__OPTIMIZE_SIZE__
-	#	define	__OPTIMIZE_SIZE__	1
-	#endif
 
 	/* __INLINE__, if defined, is the inline keyword */
 	#if !defined(__INLINE__) && defined(_WIN32) && !defined(__GNUC__)
@@ -67,14 +65,10 @@ cat{
 	#	endif
 	#endif
 
-	#if !_std_noreturn
-	#if defined(__GNUC__) && (__GNUC__ > 2 || (__GNUC__ == 2 && __GNUC_MINOR__ > 4))
-	#define noreturn __attribute__((noreturn))
-	#else
-	#define noreturn
-	#endif /* __GNUC__ */
-	#else
+	#if _std_noreturn
 	#include <stdnoreturn.h>
+	#else
+	#define noreturn /* empty */
 	#endif /* _std_noreturn */
 }end
 
@@ -82,7 +76,7 @@ if	tst - note{ <stdarg.h>+<wchar.h> works }end compile{
 		/*<NOSTDIO>*/
 		#include <stdarg.h>
 		#include <wchar.h>
-	}end 
+	}end
 elif	tst - note{ explicit <sys/va_list.h> before <stdarg.h>+<wchar.h> }end compile{
 		/*<NOSTDIO>*/
 		#include <sys/va_list.h>
@@ -138,7 +132,7 @@ tst	- -DN=1 - -DN=2 - -DN=3 - -DN=4 - -DN=5 - -DN=6 - -DN=7 - -DN=8 - -DN=0 outp
 	#endif
 
 	#define elementsof(x)	(sizeof(x)/sizeof(x[0]))
-	
+
 	static char			i_char = 1;
 	static short			i_short = 1;
 	static int			i_int = 1;
@@ -152,13 +146,13 @@ tst	- -DN=1 - -DN=2 - -DN=3 - -DN=4 - -DN=5 - -DN=6 - -DN=7 - -DN=8 - -DN=0 outp
 	static unsigned _ast_int8_t	u_long_long = 18446744073709551615;
 	#endif
 	#endif
-	
+
 	static struct
 	{
 		char*	name;
 		int	size;
 		char*	swap;
-	} int_type[] = 
+	} int_type[] =
 	{
 		"char",		sizeof(char),		(char*)&i_char,
 		"short",	sizeof(short),		(char*)&i_short,
@@ -168,18 +162,18 @@ tst	- -DN=1 - -DN=2 - -DN=3 - -DN=4 - -DN=5 - -DN=6 - -DN=7 - -DN=8 - -DN=0 outp
 		_ast_int8_str,	sizeof(_ast_int8_t),	(char*)&i_long_long,
 	#endif
 	};
-	
+
 	static int	int_size[] = { 1, 2, 4, 8 };
-	
+
 	int
-	main()
+	main(void)
 	{
-		register int	t;
-		register int	s;
-		register int	m = 1;
-		register int	b = 1;
-		register int	w = 0;
-	
+		int	t;
+		int	s;
+		int	m = 1;
+		int	b = 1;
+		int	w = 0;
+
 	#ifdef _ast_int8_t
 		unsigned _ast_int8_t	p;
 		char			buf[64];
@@ -232,7 +226,7 @@ tst	- output{
 	#include <string.h>
 	#include <sys/types.h>
 
-	#if _X86_ || _X64_ 
+	#if _X86_ || _X64_
 	#define COND		1
 	#define CONDNAME	"_X64_"
 	#else
@@ -240,13 +234,13 @@ tst	- output{
 	#endif
 
 	#define elementsof(x)	(sizeof(x)/sizeof(x[0]))
-	
+
 	static struct
 	{
 		char*	name;
 		int	size;
 		int	cond;
-	} types[] = 
+	} types[] =
 	{
 		"short",	sizeof(short),		0,
 		"int",		sizeof(int),		0,
@@ -255,15 +249,13 @@ tst	- output{
 		"pointer",	sizeof(void*),		COND * 4,
 		"float",	sizeof(float),		0,
 		"double",	sizeof(double),		0,
-	#ifdef _typ_long_double
 		"long_double",	sizeof(long double),	0,
-	#endif
 	};
-	
+
 	int
-	main()
+	main(void)
 	{
-		register int	t;
+		int	t;
 
 		for (t = 0; t < elementsof(types); t++)
 	#if COND
@@ -286,51 +278,45 @@ tst	- output{
 	exit 1
 }end
 
-tst	- -DN=1 - -DN=0 output{
+tst note{ generating _ast_flt\*_t types }end output{
 	#define _BYTESEX_H
 
 	#include <string.h>
 	#include <sys/types.h>
 
-	#if !N
-	#undef	_typ_long_double
-	#endif
-
 	#define elementsof(x)	(sizeof(x)/sizeof(x[0]))
-	
+
 	static struct
 	{
 		char*	name;
 		int	size;
-	} flt_type[] = 
+	} flt_type[] =
 	{
 		"float",	sizeof(float),
 		"double",	sizeof(double),
-	#ifdef _typ_long_double
 		"long double",	sizeof(long double),
-	#endif
 	};
-	
-	int
-	main()
-	{
-		register int	t;
-		register int	m = 1;
-	
-	#ifdef _typ_long_double
-		long double	p;
-		char		buf[64];
 
-		if (flt_type[elementsof(flt_type)-1].size <= sizeof(double))
-			return 1;
-		p = 1.12345E-55;
-		sprintf(buf, "%1.5LE", p);
-		if (strcmp(buf, "1.12345E-55"))
-			return 1;
-	#endif
-		for (t = 0; t < elementsof(flt_type); t++)
+	int
+	main(void)
+	{
+		int	t;
+		int	m = 1;
+		int	e = elementsof(flt_type);
+		if (flt_type[e - 1].size <= sizeof(double))
+			e--; /* exclude "long double" */
+		else
 		{
-			while (t < (elementsof(flt_type) - 1) && flt_type[t].size == flt_type[t + 1].size)
+			long double	p;
+			char		buf[64];
+			p = 1.12345E-55;
+			sprintf(buf, "%1.5LE", p);
+			if (strcmp(buf, "1.12345E-55"))
+				e--; /* exclude "long double" */
+		}
+		for (t = 0; t < e; t++)
+		{
+			while (t < (e - 1) && flt_type[t].size == flt_type[t + 1].size)
 				t++;
 			m = flt_type[t].size;
 			printf("#define _ast_flt%d_t		%s\n", flt_type[t].size, flt_type[t].name);
@@ -340,6 +326,9 @@ tst	- -DN=1 - -DN=0 output{
 			printf("#define _ast_fltmax_double		1\n");
 		return 0;
 	}
+}end fail{
+	echo "$0: Could not generate _ast_flt*_t types. Export IFFEFLAGS=-d1 to debug." >&2
+	exit 1
 }end
 
 typ int8_t stdint.h inttypes.h no{
@@ -390,6 +379,15 @@ typ intmax_t stdint.h inttypes.h no{
 	#undef	_typ_intmax_t
 	#define	_typ_intmax_t	1
 	typedef _ast_intmax_t intmax_t;
+}end
+typ intptr_t stdint.h inttypes.h no{
+	#undef	_typ_intptr_t
+	#define	_typ_intptr_t	1
+	#if _ast_sizeof_pointer == 8 && defined(_ast_int8_t)
+	typedef _ast_int8_t intptr_t;
+	#else
+	typedef _ast_int4_t intptr_t;
+	#endif
 }end
 typ uintmax_t stdint.h inttypes.h no{
 	#undef	_typ_uintmax_t
@@ -448,7 +446,7 @@ tst	- -DTRY=1 - -DTRY=1 -Dvoid=char - -DTRY=2 - -DTRY=3 - -DTRY=4 output{
 	}
 	#endif
 	int
-	main()
+	main(void)
 	{
 		int	r;
 
@@ -479,7 +477,7 @@ tst	- -DTRY=1 - -DTRY=1 -Dvoid=char - -DTRY=2 - -DTRY=3 - -DTRY=4 output{
 	#endif /*TRY == 2*/
 			printf("/* va_arg() va_list type */\n");
 	#endif /*TRY == 4*/
-	
+
 	#if !defined(va_copy)
 	#if defined(__va_copy)
 		printf("#ifndef va_copy\n");
@@ -500,7 +498,7 @@ tst	- -DTRY=1 - -DTRY=1 -Dvoid=char - -DTRY=2 - -DTRY=3 - -DTRY=4 output{
 	#endif
 	#endif
 	#endif
-	
+
 		printf("#endif\n");
 		return 0;
 	}
@@ -521,14 +519,6 @@ cat{
 	#		include	<inttypes.h>
 	#		endif
 	#	endif
-	#endif
-	#if !_typ_size_t
-	#	define _typ_size_t	1
-		typedef int size_t;
-	#endif
-	#if !_typ_ssize_t
-	#	define _typ_ssize_t	1
-		typedef int ssize_t;
 	#endif
 	#ifndef _AST_STD_H
 	#	define _def_map_ast	1
@@ -561,7 +551,7 @@ tst - note{ does this compiler have __builtin_unreachable() }end output{
 	 * argc should never be zero on init, but hopefully optimizers aren't that smart.
 	 */
 	#include <stdio.h>
-	#include "releaseflags.h"
+	#include "ast_release.h"
 	void testfn(int a)
 	{
 		switch(a)
@@ -583,4 +573,37 @@ tst - note{ does this compiler have __builtin_unreachable() }end output{
 	}
 }end fail{
 	echo '#define UNREACHABLE()	abort()'
+}end
+
+# TODO: remove when we require C99
+tst	has___func__ note{ does this compiler have __func__ }end execute{
+	#include <string.h>
+	int testfn(void)
+	{
+		return strcmp(__func__,"testfn")==0;
+	}
+	int main(void)
+	{
+		return !(testfn && strcmp(__func__,"main")==0);
+	}
+}end
+
+# TODO: remove when we require C99 (use __func__)
+tst	has___FUNCTION__ note{ does this compiler have __FUNCTION__ }end execute{
+	#include <string.h>
+	int testfn(void)
+	{
+		return strcmp(__FUNCTION__,"testfn")==0;
+	}
+	int main(void)
+	{
+		return !(testfn && strcmp(__FUNCTION__,"main")==0);
+	}
+}end
+
+tst	has__Static_assert note{ does this compiler have _Static_assert }end execute{
+	int main(void)
+	{
+		_Static_assert(2 + 2 == 4, "poof goes reality");
+	}
 }end
